### ISSUE TITLE
Bug 24/7 Att pinbot

### ISSUE THREAD

**Issue by andhra21231** [vhcid/amethystcraft-music#6]
At 24/7 src is error. its still out from channel.

**Comment by ariflitejek** [comment]
> At 24/7 src is error. its still out from channel.

there is an issue with the FFMPEG dependency

**Comment by andhra21231** [comment]
bug -_

**Comment by ariflitejek** [comment]
If the node is restarted, it must be correct
but idk, I've never found it

**Comment by ariflitejek** [comment]
@andhra21231 try for its premium features

**Comment by andhra21231** [comment]
hmmm...maybe at premium things, nodes never restarting ?

**Comment by ariflitejek** [comment]
> hmmm...maybe at premium things, nodes never restarting ?

yes, it all depends on your machine

**Comment by andhra21231** [comment]
ahh ok

**Comment by andhra21231** [comment]
maybe we can make some API :V

**Comment by andhra21231** [comment]
Done
